# Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
# See LICENSE in the project root for license information.

sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - '8.11.2'
before_script: "npm run build"
script: "npm run test"
os:
  - osx